po/zh_CN.po
Hello,
I improve the simplified Chinese translation. 
Now the translation is more friendly for Chinese speakers.
At the same time, I noticed a problem in [here](https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/ecb1fa44246d17a303240c3db0822b7580eedd55/po/zh_CN.po#L959).
```
#: ../src/trg-remote-prefs-dialog.c:478 ../src/trg-remote-prefs-dialog.c:572
#, c-format
msgid "Blocklist (%ld entries)"
msgstr "黑名单 (%ld 条)"
```
`%ld` should be `%li` , because `G_GINT64_FORMAT` is `li`. [[1]](https://developer.gnome.org/glib/stable/glib-Basic-Types.html#G-GINT64-FORMAT:CAPS)
It should be changed in all translations, not just simplified Chinese.
And There are few text can not be translated because #18
=> improve Simplified Chinese translation.

configure.ac
Fixes #57
When trying to understand why it happens, I noticed that `ldd` doesn't report that libGeoIP is linked to a resulting binary and transmission-remote-gtk behaves as if HAVE_GEOIP isn't defined. Well, this is my best guess of how to fix it (not sure if it's right as I have little to no experience in C and its tools).
=> Add define to enable GeoIP

src/trg-file-parser.c
Currently in "Create new torrent" window folder sizes calculated incorrectly, it's size of last file in this folder.
=> Fix folder size displaying in new torrent window

src/trg-json-widgets.c, src/trg-json-widgets.h, src/trg-remote-prefs-dialog.c, src/trg-torrent-props-dialog.c
#56.
I can't find any spinners that actually represent doubles, so just changed it to use ints instead
Have not found any side effects.
=> Fix for General download/upload speed cannot be set in preferences #56.

src/trg-menu-bar.c
I'm not sure how GTK works but I copied the function from the other shortcuts and quick testing shows that it works.
=> Add 'Ctrl-q' shortcut for quitting

src/transmission-remote-gtk.pod, src/trg-about-window.c
Trivial thing but still: "About" dialog shows links to Google Code that seized to exist. It redirects to Github but it probably won't do it forever :)
=> Change links from google code to github

src/trg-client.c
if a reverse proxy lowers header names, TRG will not parse them properly and return a 409 conflict. So I attempted to fix this by first lowering the header, and then comparing it to a lowercase x-transmission-session-id. 
I got some feedback to make sure this looked safe as well as not leaking any memory, but I am not a C programmer so I could have easily done something wrong.
=> Parse headers case insensitively

src/trg-torrent-add-url-dialog.c
This allows one to use Ctrl-U Ctrl-V and Enter to add a torrent URL without having to use the mouse.
=> Handle return(enter) key press in torrent-add-url dialog

src/trg-client.c
Since the Transmission RPC server supports it, allowing curl to use gzip compression for HTTP requests can save significant bandwidth, especially when managing a lot of torrents.
=> Enable curl gzip compression

src/trg-tree-view.h
Fix building under GCC 10 / -fno-common
* Add a `typedef` to avoid defining a variable.
Bug: https://bugs.gentoo.org/706980
=> Fix building under GCC 10 / -fno-common

data/io.github.TransmissionRemoteGtk.desktop.in
When I launch the transmission-remote-gtk app from gnome and transmission-remote-gtk is also added to favorites, it creates a duplicate icon on running tasks bar, instead of linking one to the favorite. This modification of desktop file fixes the issue.
=> link window name to an icon in app menu

src/trg-general-panel.c
I couldnt find any location where the hash of a torrent was shown, so i added it to the General tab of torrent details, which seemed the best fitting place for this
=> Add Hash information in Torrent Details > General tab

src/main.c, src/trg-client.c, src/trg-json-widgets.c, src/trg-main-window.c, src/trg-model.c, src/trg-torrent-model.c, src/trg-torrent-move-dialog.c, src/trg-torrent-props-dialog.c, src/trg-trackers-model.c, src/trg-tree-view.c
I think this fixes the most severe memory leak related to requests not freeing all data. I noticed no increase in memory use after leaving the client open for some hours, but there might be more cases of incomplete cleanup after dialogs/widgets. The gtk.suppression file seems to be hiding real memory leaks so maybe it ought to be modified.
=> Fix some memory leaks and errors

src/trg-client.c
set_session_id was mutex protected and since this is non-atomic read I think it should be protected too. Not known to have been causing problems, but safer in general.
=> Mutex protect trg_client_get_session_id

src/trg-client.c, src/trg-prefs.c, src/trg-torrent-model.c
There were errors in stderr about NULL being passed into this function,
which violates an assertion in GTK. Fix this by finding all places where
this function is called and guarding it with a NULL check.
Strictly speaking, only the fix trg-client.c mattered, the other check in
trg-torrent-model.c was not being tripped. Nevertheless, it seems like
best practices to do the check there as well.
=> fix passing NULL to json_object_unref

src/torrent-cell-renderer.c, src/trg-client.c, src/trg-main-window.c, src/util.c
The one I'm really not sure about is bedf0213024662ca00f3d9b1eea0b7bf9cf11c38. I found that function searching for a suitable way to fix that warning, and it seems to do exactly what I want, and doesn't crash. But for all I know this could be a fatally incorrect way of doing this and very leaky.
=> fix some warnings

src/trg-cell-renderer-counter.c
This string had some markup in it, so switch to g_markup_printf_escaped
to ensure that it's not printing out any warnings to stderr.
Previous warnings:
```
(transmission-remote-gtk:1483302): Gtk-WARNING **: 17:46:14.313: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```
These disappear (as far as I can tell) with this change.
=> fix gtk warning about unescaped markup

README.md, meson.build, src/trg-client.c, src/trg-files-tree-view-common.c, src/trg-main-window.c, src/trg-prefs.c, src/trg-rss-model.c, src/trg-state-selector.c, src/trg-torrent-graph.c, src/trg-trackers-tree-view.c, src/trg-tree-view.c
All of these are fixed now
```
(transmission-remote-gtk:2239211): GLib-CRITICAL **: 17:20:45.418: g_source_remove: assertion 'tag > 0' failed
(transmission-remote-gtk:2254740): Json-CRITICAL **: 17:47:05.485: json_object_get_array_member: assertion 'node != NULL' failed
Gdk-Message: 17:20:47.679: Window 0x55e079c502b0 is a temporary window without parent, application will not be able to position it on screen.
(transmission-remote-gtk:2239211): Gdk-CRITICAL **: 17:20:47.680: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```
=> fix some more warnings

extern/rss-glib/rss-document.c, extern/rss-glib/rss-item.c, src/trg-client.c, src/trg-rss-cell-renderer.c, src/trg-torrent-model.c
With these all gone, transmission-remote-gtk compiles with no warnings :)
(Which will change once `-Wdeprecated` `-Wdeprecated-declarations` are turned on)
=> Fix remaining compiler warnings

README.md, meson.build
In 6d1f20dca06124635709a0a4ed666cf967169ba2 gtk_menu_popup_at_pointer()
was introduced, which is a function introduced in 3.22. This version
exists in debian old stable so there should be no issues with
dependencies on other distros.
=> bump gtk3 dep to 3.22

README.md, meson.build, meson_options.txt, src/trg-main-window.c, src/trg-main-window.h, src/trg-preferences-dialog.c
See commit for reasoning. About removing timeouts:
- [KDE ignores timeouts](https://community.kde.org/Plasma/Notifications#Closing)
- [GNOME keeps them forever](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/112#note_82496)
- [XFCE makes them disappears after a set time](https://docs.xfce.org/apps/xfce4-notifyd/preferences)
- Others e.g. [mako](https://github.com/emersion/mako), all have configurable timeouts at the daemon level
- trg hardcoded timeout values, so that was not very user friendly to begin with
The only remaining question is: is the `GIcon` code right? Does it pull the correct icon?
=> use GNotification instead of libnotify

src/transmission-remote-gtk.pod
This is a legacy of libunique which is long gone.
I think if someone wanted this feature back it would be possible, but right now `GtkApplication` will keep unique instances from starting, so this functionality needs to be implemented via those APIs. Also, I doubt the usefulness of a feature like that. Something better might be to allow multiple daemon connections at the same time. A much larger amount of work but a much better feature.
Fixes #71
=> remove unused env from docs

meson.build, src/hig.c, src/hig.h, src/icons.c, src/trg-file-rename-dialog.c, src/trg-files-model.c, src/trg-general-panel.c, src/trg-general-panel.h, src/trg-main-window.c, src/trg-persistent-tree-view.c, src/trg-status-bar.c, src/trg-torrent-add-dialog.c, src/trg-torrent-add-url-dialog.c, src/trg-torrent-move-dialog.c, src/trg-torrent-props-dialog.c, src/trg-tree-view.c, src/win32-mailslot.c
This PR eliminates the remaining gtk3 deprecations, as well as deprecations in any library, for transmission-remote-gtk.
There are some "regressions" (UI changes) that I can see:
-  In the torrent properties dialog, the spacing between headers is missing, due to e54f443ba36863077729d4cdb987c0954b7920f6
- ~~Comment boxes in torrent properties dialog do not expand to fill the whole window 250eb6fed09577e7afb0dc49a807405ca1824227  (I might try to fix this, it does have implications)~~ fixed
- The change from `GtkTable` to `GtkGrid` removed APIs for specifying a width for columns per column, it is either one column or all columns. Right now I'm using some work around with `gtk_label_set_width_chars` and setting the width to 1 character and letting the grid expand around that. Not the …
=> Deprecations

src/util.c
In src/trg-general-panel.c comments are checked for links and then
marked up unconditonally. However, add_links_to_text() did not return a
markup-escaped string when a link was *not* found, and then passed the
raw string directly to gtk_label_set_markup(). This caused some comments
to generate warnings that the markup was invalid. Fix this by
unconditionally escaping comment strings.
=> unconditionally escape strings in add_links_to_text

src/trg-client.c
Just some misc changes I made while looking into the slow upload issue. There were already two previous bugs in this file that were fixed by `g_clear_pointer()`, so I just changed the whole file to use that where relevant. I also removed `CURL_NO_SSL` as that's not really a relevant option these days. I doubt anyone actually builds libcurl wuthout some ssl library.
=> Client cleanup

.github/workflows/c-cpp.yml, meson.build, src/win32-mailslot.c, src/win32-mailslot.h
Enable a minimum working windows build. No idea if it actually works.
Eventually, I'd like to remove `win32-mailslots.*` and drop all the win32 specific code, I think glib and gtk handles all of that for us. Also the compiler options for windows probably need to be reviewed, I blindly copied them but I don't know what half of them do.
=> windows support

src/trg-status-bar.c
Full size
Halfway resized (activates ellipsize on connection label)
As small as it gets (activates ellipsize on speed label)
Going smaller than this affects the menu bar I think, that requires some more work.
Fixes #79
=> allow status bar to resize

src/trg-main-window.c
No longer necessary now that windows supports gtk_application
activation. gtk_main* in gtk4 and needs to be removed.
=> remove leftover win32 ifdef

src/trg-torrent-add-dialog.c
This is a leftover from removing stock icons, the priority options never
had icon so this was always inconsistent. In particular, the icon names
used were leftover labels, so they didn't work at all post stock icons
purge. So, just remove the icons completely.
=> remove icons from Apply to All combobox

src/trg-torrent-add-url-dialog.c
When using the 'Add torrent from URL' functionality, it's common to already have the link in the clipboard, so use it as the default text if it looks like an http/https/magnet URL.
=> Torrent add from URL clipboard default

README.md, meson.build
Several issues with older json-glib versions have been reported, and
1.2.8 was released 4 years ago and is distros like debian stable and
ubuntu LTS.
Closes #25, Closes  #41
=> bump json-glib dependency to >= 1.2.8

data/meson.build
This was the wrong directory.
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
=> AppStream is installed in metainfo

src/trg-general-panel.c
Use grid properties to reinstate the spacing and behaviour of the
original GtkTable.
Closes: #178 
Fixes: e274990 ("change GtkTable to GtkGrid")
=> Fix spacing in torrent information panel

src/requests.c
If the torrent fails to be added on the server properly, unlinking the
torrent means that it will be lost forever. Trashing the torrent means
it could at least be restored to be downloaded with some other client.
=> Trash torrents instead of deleting them

meson.build
This is likely more "correct", and get_variable('Name') seems to not be working properly.
=> Use dep.name() instead of dep.get_variable('Name')

.github/workflows/c-cpp.yml
`ubuntu-latest` on github actions is now 22.04, which allows us to use that as the runner ID again. Furthermore, since 22.04 has meson
>=0.59.0 it lets us drop pip.
=> Udpate Linux CI for Ubuntu 22.04

src/requests.c, src/requests.h, src/trg-file-parser.c, src/trg-file-parser.h, src/trg-prefs.c, src/trg-remote-prefs-dialog.c, src/trg-stats-dialog.c, src/trg-torrent-add-dialog.c, src/upload.c, src/util.c, src/util.h
=> remove use of g_error()

src/trg-torrent-model.c
Peers connect to all available trackers by default, so we should not count them more than once by adding up reported seeds/peers from individual trackers.
Instead, we use the maximum reported value to get much more realistic stats. The probability of undercounting because different peers do not share trackers is very small and much less damaging than massive overcounting.
=> stop overcounting seeders/leechers

src/trg-stats-dialog.c
Addresses the following crash:
#0  0x0000555555574739 in TRG_IS_STATS_DIALOG (ptr=0x55555747e700) at ../src/trg-stats-dialog.h:28
#1  trg_update_stats_timerfunc (data=data@entry=0x55555747e700) at ../src/trg-stats-dialog.c:234
#2  0x00007ffff7328359 in g_timeout_dispatch
(source=0x555556638770, callback=0x555555574720 <trg_update_stats_timerfunc>, user_data=0x55555747e700)
at ../glib/gmain.c:5070
#3  0x00007ffff732212c in g_main_dispatch (context=0x5555555b1d50) at ../glib/gmain.c:3357
#4  g_main_context_dispatch_unlocked (context=0x5555555b1d50) at ../glib/gmain.c:4208
#5  0x00007ffff7382578 in g_main_context_iterate_unlocked.isra.0
(context=context@entry=0x5555555b1d50, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
at ../glib/gmain.c:4273
#6  0x00007ffff7323603 …
=> Remove timer source when stats dialog gets closed

data/meson.build
this allows the test to work in network-disconnected build environments; it's what most projects do with this kind of test so it works everywhere
=> meson: validate appdata without net

src/requests.c
This reverts cf5f5fc0f7dc0ee7c34e932e992e59413554c246 as discussed in #256. It seems that trashing torrents is a burden for some users, so I think the best path forward is to just revert this.
=> Revert: Trash torrents instead of deleting them
